# Sales & Demand Forecasting
## Notebook 2: Feature Engineering

### Objective
Prepare weekly sales data for forecasting by removing the incomplete final week and creating useful date-based features.

### Scope
- Load the processed weekly sales data.
- Remove the incomplete final week.
- Create calendar features and a continuous time index.
- Save the prepared dataset for model building.

No forecasting models are trained in this notebook.

In [4]:
import pandas as pd
from pathlib import Path

# Project paths
PROJECT_DIR = Path("..")
PROCESSED_DATA_DIR = PROJECT_DIR / "data" / "processed"

# Load weekly sales data
weekly_sales = pd.read_csv(
    PROCESSED_DATA_DIR / "weekly_sales.csv",
    parse_dates=["date"]
)

print("Original shape:", weekly_sales.shape)
print("Date range:", weekly_sales["date"].min(),
      "to", weekly_sales["date"].max())

display(weekly_sales.head())
display(weekly_sales.tail())

Original shape: (242, 2)
Date range: 2013-01-06 00:00:00 to 2017-08-20 00:00:00

        date         sales
0 2013-01-06  2.211570e+06
1 2013-01-13  2.373618e+06
2 2013-01-20  2.368007e+06
3 2013-01-27  2.272165e+06
4 2013-02-03  2.476891e+06

          date         sales
237 2017-07-23  5.744335e+06
238 2017-07-30  5.921812e+06
239 2017-08-06  6.410194e+06
240 2017-08-13  5.385402e+06
241 2017-08-20  1.523584e+06

## 1. Handle the Incomplete Final Week

The dataset ends on August 15, 2017, so the final weekly aggregate is incomplete. Remove this record before preparing the dataset for forecasting.

In [5]:
# Remove the incomplete final week
weekly_sales = weekly_sales.iloc[:-1].copy()

# Create date-based features
weekly_sales["year"] = weekly_sales["date"].dt.year
weekly_sales["month"] = weekly_sales["date"].dt.month
weekly_sales["week_of_year"] = (
    weekly_sales["date"].dt.isocalendar().week.astype(int)
)

# Continuous time index for modeling the long-term trend
weekly_sales["time_index"] = range(len(weekly_sales))

print("Shape after removing incomplete week:", weekly_sales.shape)
print("Date range:", weekly_sales["date"].min(),
      "to", weekly_sales["date"].max())

display(weekly_sales.head())

Shape after removing incomplete week: (241, 6)
Date range: 2013-01-06 00:00:00 to 2017-08-13 00:00:00

        date         sales  year  month  week_of_year  time_index
0 2013-01-06  2.211570e+06  2013      1             1           0
1 2013-01-13  2.373618e+06  2013      1             2           1
2 2013-01-20  2.368007e+06  2013      1             3           2
3 2013-01-27  2.272165e+06  2013      1             4           3
4 2013-02-03  2.476891e+06  2013      2             5           4

In [6]:
# Save prepared data
output_path = PROCESSED_DATA_DIR / "weekly_sales_features.csv"

weekly_sales.to_csv(output_path, index=False)

print("Saved to:", output_path)

Saved to: ..\data\processed\weekly_sales_features.csv

## 2. Feature Engineering Summary

- Removed the incomplete final weekly observation because the source data ends on August 15, 2017.
- Created calendar features: `year`, `month`, and `week_of_year`.
- Added `time_index`, a continuous integer that increases by one for each week. This lets Linear Regression represent the long-term trend without the week number resetting at the start of each year.
- Saved the prepared dataset as `data/processed/weekly_sales_features.csv`.

### Next Step

Use the prepared weekly sales data in Notebook 3 to build and compare a naive baseline and a Linear Regression model.